# Generated by Django 5.0.7 on 2024-07-13 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviedata',
            name='imdb_plot',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
