# Generated by Django 5.0.7 on 2024-07-14 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_image',
            field=models.ImageField(default='Images/None/Noimg.png', upload_to='Images/'),
        ),
    ]
