# Generated by Django 5.0.7 on 2024-07-15 11:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_item_item_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 15, 11, 8, 49, 732213)),
        ),
        migrations.AddField(
            model_name='item',
            name='item_last_updated_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 15, 11, 8, 49, 732227)),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_image',
            field=models.ImageField(default='Images/None/Noimg.jpeg', upload_to='Images/'),
        ),
    ]
