# Generated by Django 5.0.7 on 2024-07-15 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_item_item_created_at_item_item_last_updated_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='item_created_at',
        ),
        migrations.RemoveField(
            model_name='item',
            name='item_last_updated_at',
        ),
    ]
