# Generated by Django 5.0.7 on 2024-07-15 13:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0004_remove_item_item_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 15, 13, 0, 25, 989050)),
        ),
        migrations.AddField(
            model_name='item',
            name='item_last_updated_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 15, 13, 0, 25, 989066)),
        ),
    ]
