# Generated by Django 5.0.7 on 2024-07-15 13:08

import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0005_item_item_created_at_item_item_last_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_created_at',
            field=models.DateTimeField(db_default=django.db.models.functions.datetime.Now()),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_last_updated_at',
            field=models.DateTimeField(db_default=django.db.models.functions.datetime.Now()),
        ),
    ]
