# Generated by Django 5.0.7 on 2024-07-17 07:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0006_alter_item_item_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_created_at',
            field=models.DateTimeField(db_default=datetime.datetime(2024, 7, 17, 7, 49, 26, 474820, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_last_updated_at',
            field=models.DateTimeField(db_default=datetime.datetime(2024, 7, 17, 7, 49, 26, 474837, tzinfo=datetime.timezone.utc)),
        ),
    ]
