# Generated by Django 5.0.7 on 2024-07-17 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0007_alter_item_item_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_created_at',
            field=models.DateTimeField(auto_created=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_last_updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
