# Generated by Django 5.0.7 on 2024-07-17 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_locateion_alter_profile_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='locateion',
            new_name='location',
        ),
    ]
